DROP DATABASE IF EXISTS ice_creamDB;
DROP DATABASE IF EXISTS employeeDB;
CREATE DATABASE employeeDB;
USE employeeDB;

CREATE TABLE departments
(
  id INT NOT NULL AUTO_INCREMENT,
  dep_name VARCHAR(45) NULL,
  PRIMARY KEY (id)
);